- hosts: all
  become: yes

  tasks:
    - name: Pull the latest Docker image
      docker_image:
        name: eliotatlani31/connectly-back
        source: pull
        tag: latest

    - name: Bring up the Docker Compose services
      command: docker compose up --build -d
