- hosts: all
  become: yes

  tasks:
    - name: Stop and remove existing containers
      command: docker compose down

    - name: Force remove old Docker image
      command: docker rmi -f eliotatlani31/connectly-back:latest
      ignore_errors: yes

    - name: Pull the latest Docker image
      docker_image:
        name: eliotatlani31/connectly-back
        source: pull
        tag: latest
        force_source: yes

    - name: Bring up the Docker Compose services
      command: docker compose up --build -d
